# Site settings
title: Flynn Lauridsen
url: "https://monkmonk99.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Flynn Lauridsen
  desc: Software Engineer
  email: 
  selfie: assets/img/profile.jpg

# social
social:
  email: fl-alias@outlook.com
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: monkmonk99
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/flynnlauridsen
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "screenshot.png"
  - "README.md"
  - "gitignore"
